{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "me-token-tracker.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "me-token-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdb
  annotations:
    kubernetes.io/description: "Pod disruption budget for ME Token Tracker Discord bot service"
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "me-token-tracker.selectorLabels" . | nindent 6 }}
{{- end }}