{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "forward-auth.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "forward-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
  annotations:
    kubernetes.io/description: "Service account for forward authentication"
{{- end }}