apiVersion: v1
kind: Service
metadata:
  name: {{ include "forward-auth.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "forward-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
  annotations:
    kubernetes.io/description: "ClusterIP service for forward authentication"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "forward-auth.selectorLabels" . | nindent 4 }}