export const EnvKeys = {
  API_TOKEN: 'API_TOKEN',
  BACKEND_PORT: 'BACKEND_PORT',
  LOG_FILE_PATH: 'LOG_FILE_PATH',
  MINIO_ACCESS_KEY: 'MINIO_ACCESS_KEY',
  MINIO_HOST: 'MINIO_HOST',
  MINIO_PORT: 'MINIO_PORT',
  MINIO_PUBLIC_URL: 'MINIO_PUBLIC_URL',
  MINIO_SECRET_KEY: 'MINIO_SECRET_KEY',
  NODE_ENV: 'NODE_ENV',
} as const
