# Persistent Volumes for lilnas k8s cluster
# These define pre-allocated storage resources for various services

---
# Application configuration storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-configs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-storage
  local:
    path: /mnt/hdd1/data/k8s-volumes/app-configs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# Build cache storage for CI/CD
apiVersion: v1
kind: PersistentVolume
metadata:
  name: build-cache-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-storage
  local:
    path: /mnt/ssd1/k8s-volumes/build-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# Game servers storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-servers-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-storage
  local:
    path: /mnt/hdd1/data/k8s-volumes/game-servers
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# Google Photos storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: google-photos-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-photos-storage
  local:
    path: /mnt/ssd1/google-photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# Immich database storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-storage
  local:
    path: /mnt/ssd1/k8s-volumes/immich-db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# Immich library storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-photos-storage
  local:
    path: /mnt/ssd1/immich-library
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# Media services configuration storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-services-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-storage
  local:
    path: /mnt/hdd1/data/k8s-volumes/media-services
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# MinIO S3 storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-storage
  local:
    path: /mnt/hdd1/data/k8s-volumes/minio-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# Movies storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-media-storage
  local:
    path: /mnt/hdd1/movies
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# PostgreSQL main database storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-main-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-storage
  local:
    path: /mnt/hdd1/data/k8s-volumes/postgres-main
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# Redis cache storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cache-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-storage
  local:
    path: /mnt/ssd1/k8s-volumes/redis-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas

---
# TV shows storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-pv
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-media-storage
  local:
    path: /mnt/hdd1/tv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lilnas