http:
  middlewares:
    file-forward-auth:
      forwardAuth:
        address: "http://traefik-forward-auth:4181"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"

  routers:
    dev-nexus-code:
      rule: "Host(`nexus-code.dev.lilnas.io`)"
      entrypoints:
        - websecure
      tls: {}
      middlewares:
        - file-forward-auth
      service: dev-nexus-code

  services:
    dev-nexus-code:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5173"
