{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "apps.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "apps.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdb
  annotations:
    kubernetes.io/description: "Pod disruption budget for lilnas apps dashboard"
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "apps.selectorLabels" . | nindent 6 }}
{{- end }}