{{- if .Values.rbac }}
{{- if and .Values.rbac.create (default true .Values.rbac.ingressReader.enabled) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apps.fullname" . }}-ingress-reader
  labels:
    {{- include "apps.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apps.fullname" . }}-ingress-reader
  labels:
    {{- include "apps.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "apps.fullname" . }}-ingress-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "apps.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
