# Production environment overrides for download

namespace: lilnas-apps

# Production scaling
replicaCount: 2

# Production configuration
config:
  NODE_ENV: "production"
  MINIO_HOST: "minio-api.lilnas-core"
  MINIO_PORT: "9000"
  MINIO_PUBLIC_URL: "https://storage.lilnas.io"
  # Increase concurrent downloads for production
  MAX_DOWNLOADS: "10"
  # Keep production timezone
  TIMEZONE: "America/Los_Angeles"

# Production authentication configuration
# NOTE: Secrets must be provided via CLI flags or environment variables for security
# Do not hardcode secrets in this file
auth:
  minioAccessKey: ""  # Set via --minio-access-key or DOWNLOAD_MINIO_ACCESS_KEY
  minioSecretKey: ""  # Set via --minio-secret-key or DOWNLOAD_MINIO_SECRET_KEY

# Production resource requirements - Video processing needs significant resources
resources:
  requests:
    memory: "1Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "4000m"

# Production ingress configuration
ingress:
  hosts:
    - host: download.lilnas.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - download.lilnas.io
      secretName: download-lilnas-io-tls
  certManager:
    clusterIssuer: letsencrypt-prod

# Pod disruption budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Health check configuration with appropriate timeouts for video processing
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 90
  periodSeconds: 45
  timeoutSeconds: 20
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 3

# Production persistence configuration
persistence:
  enabled: true
  storageClass: "hdd-storage"
  accessMode: ReadWriteOnce
  size: 500Gi  # Increased for production
  mountPath: /download/videos
  annotations:
    kubernetes.io/description: "Persistent storage for downloaded videos"

# Increased temporary volume for production workloads
tmpVolume:
  enabled: true
  sizeLimit: 5Gi

# Increased cache volume for production
cacheVolume:
  enabled: true
  sizeLimit: 10Gi

# Production autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

# Common labels for prod environment
commonLabels:
  environment: prod
  tier: application

# Network policy for production security
networkPolicy:
  enabled: true
  # Allow egress for video downloads and MinIO access
  egress:
    - {}  # Allow all egress for video downloads
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: lilnas-core
      ports:
        - protocol: TCP
          port: 8080