# Development environment overrides for download

namespace: lilnas-dev

# Development configuration
config:
  NODE_ENV: "development"
  # Use localhost MinIO for development
  MINIO_PUBLIC_URL: "http://storage.localhost:9000"

# Reduced resource requirements for dev
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

# Development ingress configuration
ingress:
  hosts:
    - host: download.dev.lilnas.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - download.dev.lilnas.io
      secretName: download-dev-lilnas-io-tls
  certManager:
    clusterIssuer: letsencrypt-staging

# Faster health checks for development
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3

# Smaller persistent volume for development
persistence:
  size: 10Gi

# Common labels for dev environment
commonLabels:
  environment: dev

# Development-specific annotations
commonAnnotations:
  kubernetes.io/environment: "development"

# Enable debug logging
extraEnv:
  - name: DEBUG
    value: "true"