include:
  # Infrastructure services
  - ./infra/proxy.dev.yml
  - ./infra/shared.dev.yml

  # App services
  - ./apps/portal/deploy.dev.yml
  - ./apps/dashcam/deploy.dev.yml
  - ./apps/download/deploy.dev.yml
  - ./apps/equations/deploy.dev.yml
  - ./apps/macros/deploy.dev.yml
  - ./apps/me-token-tracker/deploy.dev.yml
  - ./apps/tdr-bot/deploy.dev.yml
  - ./apps/yoink/deploy.dev.yml
