include:
  # Infrastructure services
  - ./infra/immich.yml
  - ./infra/media.yml
  - ./infra/monitoring.yml
  - ./infra/proxy.yml
  - ./infra/shared.yml

  # App services
  - ./apps/portal/deploy.yml
  - ./apps/dashcam/deploy.yml
  - ./apps/download/deploy.yml
  - ./apps/equations/deploy.yml
  - ./apps/macros/deploy.yml
  - ./apps/me-token-tracker/deploy.yml
  - ./apps/tdr-bot/deploy.yml
  - ./apps/yoink/deploy.yml
