FROM node

ENV PNPM_VERSION="10.6.5"
ENV PNPM_HOME="/pnpm"
RUN npm install -g pnpm@${PNPM_VERSION}

COPY packages/equations/image-magick-policy.xml /etc/ImageMagick-6/policy.xml

# Latex packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        fish \
        ghostscript \
        imagemagick \
        texlive-fonts-extra \
        texlive-fonts-recommended \
        texlive-lang-all \
        texlive-latex-extra \
        texlive-latex-recommended \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8080
WORKDIR /source
ENTRYPOINT ["fish"]
