FROM node:25.0.0

ENV PNPM_VERSION="10.13.1"
ENV PNPM_HOME="/pnpm"
RUN npm install -g pnpm@${PNPM_VERSION}

COPY packages/equations/image-magick-policy.xml /etc/ImageMagick-6/policy.xml

# Latex packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        fish \
        ghostscript \
        imagemagick \
        texlive-fonts-extra \
        texlive-fonts-recommended \
        texlive-lang-all \
        texlive-latex-extra \
        texlive-latex-recommended \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/bin/yt-dlp && \
    chmod a+rx /usr/bin/yt-dlp

EXPOSE 8080
WORKDIR /source

# Add OCI image source label
LABEL org.opencontainers.image.source=https://github.com/codemonkey800/lilnas

ENTRYPOINT ["fish"]
