# GHCR (GitHub Container Registry) Secret Template
# This template creates Docker registry secrets for pulling private images from ghcr.io
# 
# Usage:
#   1. Set environment variables:
#      export GITHUB_TOKEN=ghp_your_token_here
#      export NAMESPACE=lilnas-apps
#   2. Apply with envsubst:
#      envsubst < ghcr-secret-template.yaml | kubectl apply -f -
#
# Or use the deploy-ghcr-secret.sh script to deploy to all namespaces

apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: ${NAMESPACE}
  labels:
    project: lilnas
    secret-type: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON}