services:
  equations:
    image: lilnas-dev
    command: -c "pnpm --filter=equations dev"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    volumes:
      - ../../:/source
    labels:
      - traefik.enable=true
      - traefik.http.routers.equations.rule=Host(`equations.localhost`)
      - traefik.http.services.equations.loadbalancer.server.port=8080
