export const EnvKeys = {
  BACKEND_PORT: 'BACKEND_PORT',
  DISCORD_API_TOKEN: 'DISCORD_API_TOKEN',
  DISCORD_GUILD_ID: 'DISCORD_GUILD_ID',
  NODE_ENV: 'NODE_ENV',
  CLAUDE_COMMAND: 'CLAUDE_COMMAND',
  CLAUDE_CWD: 'CLAUDE_CWD',
  AGENT_IDLE_TIMEOUT_SECONDS: 'AGENT_IDLE_TIMEOUT_SECONDS',
  AGENT_MAX_SESSIONS: 'AGENT_MAX_SESSIONS',
} as const
