export const EnvKeys = {
  BACKEND_PORT: 'BACKEND_PORT',
  DISCORD_API_TOKEN: 'DISCORD_API_TOKEN',
  DISCORD_GUILD_ID: 'DISCORD_GUILD_ID',
  NODE_ENV: 'NODE_ENV',
  CLAUDE_COMMAND: 'CLAUDE_COMMAND',
  CLAUDE_CWD: 'CLAUDE_CWD',
  AGENT_IDLE_TIMEOUT_SECONDS: 'AGENT_IDLE_TIMEOUT_SECONDS',
  AGENT_MAX_SESSIONS: 'AGENT_MAX_SESSIONS',
  // Phase A: two-process substrate
  DATABASE_PATH: 'DATABASE_PATH',
  BOT_GENERATION_ID: 'BOT_GENERATION_ID',
  SUPERVISE_BOT: 'SUPERVISE_BOT',
  // Supervisor timing knobs (all in milliseconds unless named _SECONDS)
  SUPERVISOR_START_TIMEOUT_MS: 'SUPERVISOR_START_TIMEOUT_MS',
  SUPERVISOR_SIGKILL_GRACE_MS: 'SUPERVISOR_SIGKILL_GRACE_MS',
  SUPERVISOR_STABLE_WINDOW_MS: 'SUPERVISOR_STABLE_WINDOW_MS',
  SUPERVISOR_BACKOFF_BASE_MS: 'SUPERVISOR_BACKOFF_BASE_MS',
  SUPERVISOR_BACKOFF_MAX_MS: 'SUPERVISOR_BACKOFF_MAX_MS',
  SUPERVISOR_CRASH_LOOP_WINDOW_MS: 'SUPERVISOR_CRASH_LOOP_WINDOW_MS',
  SUPERVISOR_CRASH_LOOP_THRESHOLD: 'SUPERVISOR_CRASH_LOOP_THRESHOLD',
  SUPERVISOR_LIVENESS_POLL_MS: 'SUPERVISOR_LIVENESS_POLL_MS',
  // Bot heartbeat + command poller timing
  BOT_HEARTBEAT_MS: 'BOT_HEARTBEAT_MS',
  BOT_COMMAND_POLL_MS: 'BOT_COMMAND_POLL_MS',
  // Heartbeat staleness threshold = heartbeatMs + busy_timeout + margin
  BOT_HEARTBEAT_STALE_THRESHOLD_MS: 'BOT_HEARTBEAT_STALE_THRESHOLD_MS',
} as const
