export const EnvKeys = {
  BACKEND_PORT: 'BACKEND_PORT',
  // Phase C: path to the 32-byte AES-256-GCM master key file (chmod 600,
  // outside the Tier-1 backup tree).
  TDR_CODE_MASTER_KEY_FILE: 'TDR_CODE_MASTER_KEY_FILE',
  DISCORD_API_TOKEN: 'DISCORD_API_TOKEN',
  DISCORD_GUILD_ID: 'DISCORD_GUILD_ID',
  // Phase D: Discord OAuth2 app credentials (Better Auth Discord provider).
  // Distinct from DISCORD_API_TOKEN (the bot token) — these come from the
  // same Discord Application's OAuth2 page, not the Bot page.
  DISCORD_CLIENT_ID: 'DISCORD_CLIENT_ID',
  DISCORD_CLIENT_SECRET: 'DISCORD_CLIENT_SECRET',
  // Phase D: Better Auth session-signing secret (generated, not from Discord)
  // and the app's public base URL used to build OAuth redirect URIs and
  // derive secure-cookie defaults.
  BETTER_AUTH_SECRET: 'BETTER_AUTH_SECRET',
  BETTER_AUTH_URL: 'BETTER_AUTH_URL',
  NODE_ENV: 'NODE_ENV',
  CLAUDE_COMMAND: 'CLAUDE_COMMAND',
  CLAUDE_CWD: 'CLAUDE_CWD',
  AGENT_IDLE_TIMEOUT_SECONDS: 'AGENT_IDLE_TIMEOUT_SECONDS',
  AGENT_MAX_SESSIONS: 'AGENT_MAX_SESSIONS',
  // Phase A: two-process substrate
  DATABASE_PATH: 'DATABASE_PATH',
  BOT_GENERATION_ID: 'BOT_GENERATION_ID',
  SUPERVISE_BOT: 'SUPERVISE_BOT',
  // Supervisor timing knobs (all in milliseconds unless named _SECONDS)
  SUPERVISOR_START_TIMEOUT_MS: 'SUPERVISOR_START_TIMEOUT_MS',
  SUPERVISOR_SIGKILL_GRACE_MS: 'SUPERVISOR_SIGKILL_GRACE_MS',
  SUPERVISOR_STABLE_WINDOW_MS: 'SUPERVISOR_STABLE_WINDOW_MS',
  SUPERVISOR_BACKOFF_BASE_MS: 'SUPERVISOR_BACKOFF_BASE_MS',
  SUPERVISOR_BACKOFF_MAX_MS: 'SUPERVISOR_BACKOFF_MAX_MS',
  SUPERVISOR_CRASH_LOOP_WINDOW_MS: 'SUPERVISOR_CRASH_LOOP_WINDOW_MS',
  SUPERVISOR_CRASH_LOOP_THRESHOLD: 'SUPERVISOR_CRASH_LOOP_THRESHOLD',
  SUPERVISOR_LIVENESS_POLL_MS: 'SUPERVISOR_LIVENESS_POLL_MS',
  // Bot heartbeat + command poller timing
  BOT_HEARTBEAT_MS: 'BOT_HEARTBEAT_MS',
  BOT_COMMAND_POLL_MS: 'BOT_COMMAND_POLL_MS',
  // Heartbeat staleness threshold = heartbeatMs + busy_timeout + margin
  BOT_HEARTBEAT_STALE_THRESHOLD_MS: 'BOT_HEARTBEAT_STALE_THRESHOLD_MS',
} as const
