# Development environment overrides for turbo-cache

namespace: lilnas-dev

# Development configuration
config:
  logLevel: "debug"

# Reduced resource requirements for dev
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Development ingress configuration
ingress:
  host: turbo.dev.lilnas.io
  tls:
    issuer: letsencrypt-staging

# Common labels for dev environment
commonLabels:
  environment: dev