apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lilnas-core

resources:
  - ../base

labels:
  - pairs:
      environment: prod

# Production-specific patches
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: forward-auth
    spec:
      replicas: 2
      template:
        spec:
          containers:
          - name: forward-auth
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: forward-auth-config
    data:
      log-level: "warn"