apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lilnas-dev

resources:
  - ../base

commonLabels:
  environment: dev

# Development-specific patches
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: forward-auth
    spec:
      replicas: 1
      template:
        spec:
          containers:
          - name: forward-auth
            resources:
              requests:
                memory: "32Mi"
                cpu: "25m"
              limits:
                memory: "64Mi"
                cpu: "50m"

# Development-specific configuration
configMapGenerator:
  - name: forward-auth-config
    behavior: merge
    literals:
      - log-level=debug
      - insecure-cookie=true

# Patch ingress for dev domain
patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: forward-auth
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: auth.dev.lilnas.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: auth.dev.lilnas.io
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging