services:
  download:
    image: lilnas-dev
    command: -c "pnpm --filter=download dev"
    restart: unless-stopped
    env_file:
      - .env.download
    volumes:
      - ../:/source
    labels:
      - traefik.enable=true
      - traefik.http.routers.download.rule=Host(`download.localhost`)
      - traefik.http.services.download.loadbalancer.server.port=8080

  tdr-bot:
    image: lilnas-dev
    command: -c "pnpm --filter=tdr-bot dev"
    restart: unless-stopped
    env_file:
      - .env.tdr-bot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/source
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdr.rule=Host(`tdr.localhost`)
      - traefik.http.services.tdr.loadbalancer.server.port=8080
