services:
  dev:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    command: -c "cd /source/packages/${SERVICE} && pnpm dev"
    env_file:
      - .env.${SERVICE}
    ports:
      - 8080:8080
    volumes:
      - ../:/source
