services:
  code-server:
    image: codercom/code-server
    volumes:
      - ../code-server/config:/home/coder/.config
      - ../code-server/project:/home/coder/project
    restart: on-failure
    labels:
      - traefik.enable=true
      - traefik.http.services.code-server.loadbalancer.server.port=8080
      - traefik.http.routers.code-server.rule=Host(`code.lilnas.io`)
      - traefik.http.routers.code-server.entrypoints=websecure
      - traefik.http.routers.code-server.tls.certresolver=le
