# Vanilla Minecraft Server Configuration
# Previous SevTech: Ages modpack backed up to: /storage/backup-archive/minecraft-sevtech-backup-20250816.7z
services:
  minecraft:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    restart: unless-stopped

    ports:
      - 25565:25565

    environment:
      # Core server settings
      VERSION: LATEST
      TYPE: VANILLA
      EULA: TRUE
      
      # Server optimization
      MEMORY: 2G
      DIFFICULTY: normal
      MAX_PLAYERS: 20
      MOTD: "Vanilla Minecraft Server"
      
      # Remote console access
      ENABLE_RCON: true
      RCON_PASSWORD: minecraft
      
      # Previous SevTech: Ages modpack configuration (commented out, backed up)
      # CF_SLUG: sevtech-ages
      # CF_API_KEY: '$$2a$$10$$KsGznF2XwmjdbLQsyiJEPuTs5mMpYSsJtmKK0yuNTeMYh9eOb6sqG'

    volumes:
      - /storage/app-data/minecraft:/data
