services:
  traefik:
    image: traefik
    command:
      - --api=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=jeremyasuncion808@gmail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Dashboard
      - traefik.http.routers.traefik.rule=Host(`traefik.lilnas.io`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.middlewares=forward-auth

      # global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https

      # middleware redirect http -> https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true

      # sts middleware
      - traefik.http.middlewares.servicestls.headers.stsincludesubdomains=false
      - traefik.http.middlewares.servicestls.headers.stspreload=true
      - traefik.http.middlewares.servicestls.headers.stsseconds=15552001
      - traefik.http.middlewares.servicestls.headers.isdevelopment=false

      # https proto
      - 'traefik.http.middlewares.testHeader.headers.customrequestheaders.X-Forwarded-Proto=https'
      - 'traefik.http.middlewares.testHeader.headers.framedeny=true'
      - 'traefik.http.middlewares.testHeader.headers.sslredirect=true'

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2.1.0
    env_file:
      - .env
    labels:
      - traefik.http.routers.auth.rule=Host(`auth.lilnas.io`)
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.routers.auth.tls.certresolver=le
      - traefik.http.routers.auth.service=auth@docker
      - traefik.http.services.auth.loadbalancer.server.port=4181
      - traefik.http.middlewares.forward-auth.forwardauth.address=http://traefik-forward-auth:4181
      - traefik.http.middlewares.forward-auth.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User
      - traefik.http.routers.auth.middlewares=forward-auth
