services:
  storage:
    image: minio/minio
    restart: unless-stopped
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env.storage
    volumes:
      - ../data/storage:/data
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - traefik.enable=true

      # API Access
      - traefik.http.routers.storage.rule=Host(`storage.lilnas.io`)
      - traefik.http.routers.storage.entrypoints=websecure
      - traefik.http.routers.storage.tls.certresolver=le
      - traefik.http.routers.storage.service=storage
      - traefik.http.services.storage.loadbalancer.server.port=9000

      # Dashboard
      - traefik.http.routers.storage-admin.rule=Host(`storage-admin.lilnas.io`)
      - traefik.http.routers.storage-admin.entrypoints=websecure
      - traefik.http.routers.storage-admin.tls.certresolver=le
      - traefik.http.routers.storage-admin.service=storage-admin
      - traefik.http.services.storage-admin.loadbalancer.server.port=9001

  turbo:
    image: ducktors/turborepo-remote-cache
    restart: unless-stopped
    env_file:
      - .env.turbo
    labels:
      - traefik.enable=true
      - traefik.http.routers.turbo.rule=Host(`turbo.lilnas.io`)
      - traefik.http.routers.turbo.entrypoints=websecure
      - traefik.http.routers.turbo.tls.certresolver=le
      - traefik.http.services.turbo.loadbalancer.server.port=3000
