{{- if .Values.staging.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.staging.name }}
  labels:
    {{- include "cert-manager-issuers.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.email }}
    server: {{ .Values.staging.server }}
    privateKeySecretRef:
      name: {{ .Values.staging.privateKeySecretRef.name }}
    solvers:
      - {{ .Values.solver.type }}:
          ingress:
            class: {{ .Values.solver.ingress.class }}
{{- end }}