export const EnvKeys = {
  BACKEND_PORT: 'BACKEND_PORT',
  EMBY_API_KEY: 'EMBY_API_KEY',
  EMBY_URL: 'EMBY_URL',
  EMBY_USERNAME: 'EMBY_USERNAME',
  NODE_ENV: 'NODE_ENV',
  THEATER_PASSWORD: 'THEATER_PASSWORD',
  THEATER_SESSION_SECRET: 'THEATER_SESSION_SECRET',
} as const
