# GitHub Actions Service Account and RBAC Configuration
# This configuration creates a dedicated service account for GitHub Actions
# with read-only permissions to Kubernetes resources.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: default
  labels:
    app: github-actions
    component: ci-cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions-reader
  labels:
    app: github-actions
    component: ci-cd
rules:
  # Core resources - read-only access
  - apiGroups: [""]
    resources: 
      - pods
      - pods/log
      - pods/status
      - services
      - endpoints
      - configmaps
      - secrets
      - persistentvolumes
      - persistentvolumeclaims
      - nodes
      - events
      - namespaces
    verbs: ["get", "list", "watch"]
  
  # Apps resources - read-only access
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/status
      - replicasets
      - replicasets/status
      - statefulsets
      - statefulsets/status
      - daemonsets
      - daemonsets/status
    verbs: ["get", "list", "watch"]
  
  # Networking resources - read-only access
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch"]
  
  # Extensions and batch resources - read-only access
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  
  # Custom resources that might be relevant
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-binding
  labels:
    app: github-actions
    component: ci-cd
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: default
roleRef:
  kind: ClusterRole
  name: github-actions-reader
  apiGroup: rbac.authorization.k8s.io