# GitHub Actions Service Account with Extended Permissions
# This configuration provides write access for advanced operations.
# Apply this ONLY if you need Claude Code to perform write operations.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions-extended
  labels:
    app: github-actions
    component: ci-cd
    permission-level: extended
rules:
  # Core resources - extended access
  - apiGroups: [""]
    resources: 
      - pods
      - pods/log
      - pods/status
      - services
      - endpoints
      - configmaps
      - persistentvolumeclaims
      - events
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Pod-specific actions
  - apiGroups: [""]
    resources:
      - pods/exec
      - pods/portforward
    verbs: ["create"]
  
  # Apps resources - extended access
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/status
      - deployments/scale
      - replicasets
      - replicasets/status
      - statefulsets
      - statefulsets/status
      - statefulsets/scale
      - daemonsets
      - daemonsets/status
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Networking resources - extended access
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Batch resources - extended access
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Read-only access to sensitive resources
  - apiGroups: [""]
    resources:
      - secrets
      - nodes
      - namespaces
      - persistentvolumes
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-extended-binding
  labels:
    app: github-actions
    component: ci-cd
    permission-level: extended
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: default
roleRef:
  kind: ClusterRole
  name: github-actions-extended
  apiGroup: rbac.authorization.k8s.io