{{- $global := .Values.global -}}
{{- $projectName := .Values.global.projectName -}}

{{/*
Core namespace
*/}}
{{- if .Values.namespaces.core.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.core.name }}
  labels:
    {{- include "namespaces.namespaceLabels" (dict "namespace" .Values.namespaces.core "global" $global "projectName" $projectName) | nindent 4 }}
  {{- $annotations := include "namespaces.namespaceAnnotations" (dict "namespace" .Values.namespaces.core "global" $global) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}

{{/*
Apps namespace
*/}}
{{- if .Values.namespaces.apps.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.apps.name }}
  labels:
    {{- include "namespaces.namespaceLabels" (dict "namespace" .Values.namespaces.apps "global" $global "projectName" $projectName) | nindent 4 }}
  {{- $annotations := include "namespaces.namespaceAnnotations" (dict "namespace" .Values.namespaces.apps "global" $global) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}

{{/*
Media namespace
*/}}
{{- if .Values.namespaces.media.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.media.name }}
  labels:
    {{- include "namespaces.namespaceLabels" (dict "namespace" .Values.namespaces.media "global" $global "projectName" $projectName) | nindent 4 }}
  {{- $annotations := include "namespaces.namespaceAnnotations" (dict "namespace" .Values.namespaces.media "global" $global) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}

{{/*
Monitoring namespace
*/}}
{{- if .Values.namespaces.monitoring.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.monitoring.name }}
  labels:
    {{- include "namespaces.namespaceLabels" (dict "namespace" .Values.namespaces.monitoring "global" $global "projectName" $projectName) | nindent 4 }}
  {{- $annotations := include "namespaces.namespaceAnnotations" (dict "namespace" .Values.namespaces.monitoring "global" $global) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}

{{/*
Dev namespace
*/}}
{{- if .Values.namespaces.dev.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.dev.name }}
  labels:
    {{- include "namespaces.namespaceLabels" (dict "namespace" .Values.namespaces.dev "global" $global "projectName" $projectName) | nindent 4 }}
  {{- $annotations := include "namespaces.namespaceAnnotations" (dict "namespace" .Values.namespaces.dev "global" $global) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}

{{/*
Custom namespaces
*/}}
{{- range .Values.customNamespaces }}
{{- if .enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- include "namespaces.namespaceLabels" (dict "namespace" . "global" $global "projectName" $projectName) | nindent 4 }}
  {{- $annotations := include "namespaces.namespaceAnnotations" (dict "namespace" . "global" $global) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}