services:
  tdr-bot:
    image: lilnas-dev
    command: -c "pnpm --filter=tdr-bot dev"
    restart: unless-stopped
    env_file:
      - ../../infra/.env.tdr-bot
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/source
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdr.rule=Host(`tdr.localhost`)
      - traefik.http.services.tdr.loadbalancer.server.port=8080
