apiVersion: v2
name: me-token-tracker
description: A Helm chart for lilnas ME Token Tracker - Discord bot for cryptocurrency token tracking
type: application
version: 0.1.0
appVersion: "0.2.0"
home: https://github.com/codemonkey800/lilnas
icon: https://raw.githubusercontent.com/codemonkey800/lilnas/main/docs/logo.png
keywords:
  - discord
  - bot
  - cryptocurrency
  - token
  - tracking
  - nestjs
sources:
  - https://github.com/codemonkey800/lilnas/tree/main/packages/me-token-tracker
maintainers:
  - name: lilnas
    email: support@lilnas.io

dependencies:
  - name: lilnas-common
    version: '0.1.0'
    repository: 'file://../_library'