# Production values for me-token-tracker
# Override default values for production environment

# Use stable image tag in production
image:
  pullPolicy: IfNotPresent

# Production resource limits - higher for reliability
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

# Production health check configuration - more conservative
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 15
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

# Production configuration
config:
  NODE_ENV: "production"
  TZ: "America/Los_Angeles"

# Production pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Production autoscaling (disabled by default)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 85

# Production volume configuration
tmpVolume:
  enabled: true
  sizeLimit: 200Mi

cacheVolume:
  enabled: true
  sizeLimit: 200Mi

# Production network policy
networkPolicy:
  enabled: true
  egress:
    # Allow DNS resolution
    - to: []
      ports:
      - protocol: UDP
        port: 53
    # Allow HTTPS for Discord API
    - to: []
      ports:
      - protocol: TCP
        port: 443
    # Allow HTTP for health checks
    - to: []
      ports:
      - protocol: TCP
        port: 80

# Production annotations
commonAnnotations:
  kubernetes.io/description: "ME Token Tracker Discord bot - Production"
  deployed-by: "helm"
  environment: "production"

# Production labels
commonLabels:
  environment: "production"
  tier: "bot"