apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dashcam.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dashcam.labels" . | nindent 4 }}
  annotations:
    {{- include "dashcam.annotations" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "dashcam.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "dashcam.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dashcam.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot | default true }}
        runAsUser: {{ .Values.podSecurityContext.runAsUser | default 101 }}
        runAsGroup: {{ .Values.podSecurityContext.runAsGroup | default 101 }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup | default 101 }}
        {{- with .Values.podSecurityContext.seccompProfile }}
        seccompProfile:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation | default false }}
          readOnlyRootFilesystem: {{ .Values.containerSecurityContext.readOnlyRootFilesystem | default true }}
          capabilities:
            drop:
            {{- range .Values.containerSecurityContext.capabilities.drop | default (list "ALL") }}
            - {{ . }}
            {{- end }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.tmpVolume.enabled }}
        - name: tmp
          mountPath: /tmp
        {{- end }}
        {{- if .Values.cacheVolume.enabled }}
        - name: cache
          mountPath: {{ .Values.cacheVolume.mountPath }}
        {{- end }}
        {{- with .Values.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.tmpVolume.enabled }}
      - name: tmp
        emptyDir:
          {{- with .Values.tmpVolume.sizeLimit }}
          sizeLimit: {{ . }}
          {{- end }}
      {{- end }}
      {{- if .Values.cacheVolume.enabled }}
      - name: cache
        emptyDir:
          {{- with .Values.cacheVolume.sizeLimit }}
          sizeLimit: {{ . }}
          {{- end }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}