apiVersion: v1
kind: Service
metadata:
  name: {{ include "dashcam.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dashcam.labels" . | nindent 4 }}
  annotations:
    {{- include "dashcam.annotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "dashcam.selectorLabels" . | nindent 4 }}