services:
  me-token-tracker:
    build:
      context: ../..
      dockerfile: apps/me-token-tracker/Dockerfile
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env.prod
