services:
  me-token-tracker:
    image: lilnas-dev
    command: -c "pnpm --filter=me-token-tracker dev"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    volumes:
      - ../../:/source
