# Production environment overrides for sabnzbd
# This overrides the default values.yaml for production environment

# Production namespace
namespace: lilnas-media

# Production configuration
config:
  # Production timezone (keep as configured)
  TZ: "America/Los_Angeles"
  # PUID and PGID for file permissions (keep as configured)
  PUID: "1000"
  PGID: "1000"

# Production ingress configuration (already correctly configured for production domain)
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # NO forward-auth middleware - SABnzbd handles its own authentication
    kubernetes.io/description: "Production ingress for SABnzbd service"
  hosts:
    - host: sabnzbd.lilnas.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sabnzbd.lilnas.io
      secretName: sabnzbd-lilnas-io-tls
  certManager:
    clusterIssuer: letsencrypt-prod

# Production resource requirements - SABnzbd handles large downloads and extraction
resources:
  requests:
    memory: "512Mi"
    cpu: "300m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

# Production health check configuration with appropriate timeouts for download processing
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 150
  periodSeconds: 45
  timeoutSeconds: 15
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 90
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

# Production persistence configuration - larger storage for downloads
persistence:
  enabled: true
  storageClass: "hdd-media-storage"
  accessModes:
    - ReadWriteOnce
  size: 50Gi  # Increased for production download storage
  mountPath: /config
  annotations:
    kubernetes.io/description: "Persistent storage for SABnzbd configuration and incomplete downloads"

# Increased temporary volume for production download processing
tmpVolume:
  enabled: true
  sizeLimit: 5Gi

# Pod disruption budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Common labels for production environment
commonLabels:
  environment: prod
  tier: media

# Common annotations for production
commonAnnotations:
  environment: production
  service-type: media-downloader

# Network policy for production security
networkPolicy:
  enabled: true
  # Allow egress for Usenet connections and external APIs
  egress:
    - {}  # Allow all egress for Usenet providers and NZB indexers
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: lilnas-core
      ports:
        - protocol: TCP
          port: 8080