/**
 * @fileoverview Main types module exports
 *
 * This module serves as the central export point for all type definitions,
 * providing a clean interface for importing types throughout the application.
 */

// Export enum types - excluding conflicting ones that are redefined elsewhere
export {
  ActionType,
  ActivityType,
  ApiClientType,
  ApplicationCommandType,
  AuditLogEvent,
  ButtonStyle,
  CacheStrategy,
  ComponentType,
  ContentType,
  DiscordErrorCodes,
  EmbedType,
  EventType,
  InteractionType,
  MediaStatusType,
  MediaType,
  MessageFlags,
  MinimumAvailabilityType,
  MonitorType,
  PermissionFlagsBits,
  Priority,
  QueueStatusType,
  RateLimitStrategy,
  SeriesType,
  ServiceHealthStatus,
  TextInputStyle,
  TrackedDownloadStateType,
  TrackedDownloadStatusType,
  UserFlags,
  ValidationErrorType,
  WebhookType,
} from './enums'

// Export Discord types
export * from './discord.types'

// Export media types - excluding the generic MediaItemId to avoid conflict with branded version
export type {
  AddOptions,
  AnyMediaFile,
  AnyMediaRequest,
  ApiResponse,
  BaseSearchResult,
  CommonMediaProperties,
  DiskSpace,
  EmbyChapter,
  EmbyItem,
  EmbyMediaStream,
  EmbySearchHint,
  EmbySearchResult,
  EmbyTrailer,
  EmbyUserData,
  EpisodeFile,
  EpisodeRange,
  EpisodeSpecification,
  ExtractMediaType,
  FileInfoForMediaType,
  FilterMediaItemsByType,
  FormatItem,
  HasDiscriminant,
  LanguageProfile,
  MediaApiEndpoints,
  MediaFileInfo,
  MediaImage,
  MediaInfo,
  MediaItem,
  MediaItemFactory,
  MediaItemForType,
  MediaRequest,
  MediaRequestId,
  MediaSearchResult,
  MediaStatus,
  MovieFile,
  MovieItem,
  MovieRequest,
  MovieSearchResult,
  MovieSearchResultContainer,
  PaginatedApiResponse,
  PartialFields,
  Quality,
  QualityInfo,
  QualityProfile,
  QualityProfileItem,
  QualityRevision,
  QueueItem,
  Rating,
  ReadonlyExcept,
  RequiredFields,
  RootFolder,
  SearchResult,
  SearchResultForMediaType,
  SearchSeason,
  Season,
  SeasonStatistics,
  SeriesItem,
  SeriesRequest,
  SeriesSearchResult,
  SeriesSearchResultContainer,
  StatusMessage,
  StorageMetrics,
  SystemStatus,
  Tag,
  TypedMediaRequest,
  UnmappedFolder,
} from '../media/interfaces/media.types'

// Export all branded types (includes the branded MediaItemId)
export * from './branded'

// Export specific type guards to avoid conflicts with branded types
export {
  isArrayResponse,
  isAxiosError,
  isAxiosErrorWithResponse,
  isEmbyItem,
  isErrorCategory,
  isErrorClassification,
  isErrorSeverity,
  isErrorType,
  isMediaStatus,
  isMediaStatusType,
  isMediaType,
  isMovieItem,
  isMovieSearchResult,
  isMovieSearchResultContainer,
  isNetworkError,
  isNonEmptyString,
  isNonNegativeInteger,
  isNonNullObject,
  isPaginatedResponse,
  isPositiveInteger,
  isQueueItem,
  isQueueStatusType,
  isSeriesItem,
  isSeriesSearchResult,
  isSeriesSearchResultContainer,
  isTimeoutError,
  isTrackedDownloadStateType,
  isTrackedDownloadStatusType,
} from './type-guards'

// Export advanced types - excluding conflicting HttpMethod and LogLevel
export type {
  Add,
  ApiClientMethods,
  ApiEndpoint,
  ArrayElement,
  ArrayHKT,
  Assert,
  AsyncResult,
  Compatible,
  Compose,
  ContextualLog,
  Curry,
  DeepPartial,
  DeepRequired,
  DiscriminantValues,
  EnvVar,
  Equals,
  ErrorHandlerForCategory,
  EventHandlers,
  ExhaustiveCheck,
  FilterByDiscriminant,
  Functor,
  Getters,
  HasIntersection,
  HKT,
  Immutable,
  IsArray,
  IsFunction,
  IsPromise,
  KeysOfType,
  Kind,
  Length,
  MediaApiResponses,
  MediaApiRoute,
  MediaItemProcessor,
  Mutable,
  NonNullable,
  Nullable,
  NullableProperties,
  Option,
  Optional,
  OptionHKT,
  OverloadResolver,
  Paths,
  PathValue,
  Prefixed,
  PromiseHKT,
  PropertiesOfType,
  Required,
  Result,
  SafeReturnType,
  ServiceConfigurations,
  Setters,
  Suffixed,
  TupleToUnion,
  TypeTests,
  UnionToIntersection,
  UnwrapPromise,
  ValidatedBrand,
  VersionedEndpoint,
} from './advanced'

// Export the enum versions of HttpMethod and LogLevel to maintain compatibility
export { HttpMethod, LogLevel } from './enums'
