// AUTO-GENERATED by `scripts/seats.ts` from `public/models/cinema.glb` --
// do not hand-edit the SEATS array below. The three constants and the two
// helper functions after it are normal hand-maintained code that this
// generator also owns writing out (PLAN.md's F1 section: "generated, but
// written as a normal committed source file"); re-run after cinema.glb's
// seat geometry changes:
//
//   pnpm --filter @lilnas/theater seats
//
// See PLAN.md's "Seat data -- measured, not assumed" section and
// ORCHESTRATE.md §1's seats.ts contract block.

import { MathUtils, Vector3 } from 'three'

import { gazeAlignment } from './gaze'

export type Seat = {
  id: string // `r{row}s{col}`, row 0..5, col 0..6
  row: number
  col: number
  cushion: [number, number, number] // world-space cushion-top centre
  yaw: number // 0 for every seat (all face +Z / the screen)
}

export const SEATS: Seat[] = [
  { id: 'r0s0', row: 0, col: 0, cushion: [-2.3498, 1.178, 0.7134], yaw: 0 },
  { id: 'r0s1', row: 0, col: 1, cushion: [-1.9089, 1.178, 0.7134], yaw: 0 },
  { id: 'r0s2', row: 0, col: 2, cushion: [-1.4672, 1.178, 0.7134], yaw: 0 },
  { id: 'r0s3', row: 0, col: 3, cushion: [-1.0262, 1.178, 0.7134], yaw: 0 },
  { id: 'r0s4', row: 0, col: 4, cushion: [-0.5853, 1.178, 0.7134], yaw: 0 },
  { id: 'r0s5', row: 0, col: 5, cushion: [-0.1444, 1.178, 0.7134], yaw: 0 },
  { id: 'r0s6', row: 0, col: 6, cushion: [0.2965, 1.178, 0.7134], yaw: 0 },
  { id: 'r1s0', row: 1, col: 0, cushion: [-2.3498, 1.478, -0.1366], yaw: 0 },
  { id: 'r1s1', row: 1, col: 1, cushion: [-1.9089, 1.478, -0.1366], yaw: 0 },
  { id: 'r1s2', row: 1, col: 2, cushion: [-1.4672, 1.478, -0.1366], yaw: 0 },
  { id: 'r1s3', row: 1, col: 3, cushion: [-1.0262, 1.478, -0.1366], yaw: 0 },
  { id: 'r1s4', row: 1, col: 4, cushion: [-0.5853, 1.478, -0.1366], yaw: 0 },
  { id: 'r1s5', row: 1, col: 5, cushion: [-0.1444, 1.478, -0.1366], yaw: 0 },
  { id: 'r1s6', row: 1, col: 6, cushion: [0.2965, 1.478, -0.1366], yaw: 0 },
  { id: 'r2s0', row: 2, col: 0, cushion: [-2.3498, 1.778, -0.9866], yaw: 0 },
  { id: 'r2s1', row: 2, col: 1, cushion: [-1.9089, 1.778, -0.9866], yaw: 0 },
  { id: 'r2s2', row: 2, col: 2, cushion: [-1.4672, 1.778, -0.9866], yaw: 0 },
  { id: 'r2s3', row: 2, col: 3, cushion: [-1.0262, 1.778, -0.9866], yaw: 0 },
  { id: 'r2s4', row: 2, col: 4, cushion: [-0.5853, 1.778, -0.9866], yaw: 0 },
  { id: 'r2s5', row: 2, col: 5, cushion: [-0.1444, 1.778, -0.9866], yaw: 0 },
  { id: 'r2s6', row: 2, col: 6, cushion: [0.2965, 1.778, -0.9866], yaw: 0 },
  { id: 'r3s0', row: 3, col: 0, cushion: [-2.3498, 2.078, -1.8366], yaw: 0 },
  { id: 'r3s1', row: 3, col: 1, cushion: [-1.9089, 2.078, -1.8366], yaw: 0 },
  { id: 'r3s2', row: 3, col: 2, cushion: [-1.4672, 2.078, -1.8366], yaw: 0 },
  { id: 'r3s3', row: 3, col: 3, cushion: [-1.0262, 2.078, -1.8366], yaw: 0 },
  { id: 'r3s4', row: 3, col: 4, cushion: [-0.5853, 2.078, -1.8366], yaw: 0 },
  { id: 'r3s5', row: 3, col: 5, cushion: [-0.1444, 2.078, -1.8366], yaw: 0 },
  { id: 'r3s6', row: 3, col: 6, cushion: [0.2965, 2.078, -1.8366], yaw: 0 },
  { id: 'r4s0', row: 4, col: 0, cushion: [-2.3498, 2.378, -2.6866], yaw: 0 },
  { id: 'r4s1', row: 4, col: 1, cushion: [-1.9089, 2.378, -2.6866], yaw: 0 },
  { id: 'r4s2', row: 4, col: 2, cushion: [-1.4672, 2.378, -2.6866], yaw: 0 },
  { id: 'r4s3', row: 4, col: 3, cushion: [-1.0262, 2.378, -2.6866], yaw: 0 },
  { id: 'r4s4', row: 4, col: 4, cushion: [-0.5853, 2.378, -2.6866], yaw: 0 },
  { id: 'r4s5', row: 4, col: 5, cushion: [-0.1444, 2.378, -2.6866], yaw: 0 },
  { id: 'r4s6', row: 4, col: 6, cushion: [0.2965, 2.378, -2.6866], yaw: 0 },
  { id: 'r5s0', row: 5, col: 0, cushion: [-2.3498, 2.678, -3.5366], yaw: 0 },
  { id: 'r5s1', row: 5, col: 1, cushion: [-1.9089, 2.678, -3.5366], yaw: 0 },
  { id: 'r5s2', row: 5, col: 2, cushion: [-1.4672, 2.678, -3.5366], yaw: 0 },
  { id: 'r5s3', row: 5, col: 3, cushion: [-1.0262, 2.678, -3.5366], yaw: 0 },
  { id: 'r5s4', row: 5, col: 4, cushion: [-0.5853, 2.678, -3.5366], yaw: 0 },
  { id: 'r5s5', row: 5, col: 5, cushion: [-0.1444, 2.678, -3.5366], yaw: 0 },
  { id: 'r5s6', row: 5, col: 6, cushion: [0.2965, 2.678, -3.5366], yaw: 0 },
]

// Local camera height above the cushion when seated. Eyeballed starting
// value, documented as needing one visual pass -- this app's established
// convention for "no live browser to measure against" (cf. Avatar.tsx's
// NATURAL_SPEED_MPS).
export const SEATED_EYE_ABOVE_CUSHION = 0.65

// How close to a seat's cushion (from the camera) you must be to claim it
// (D9). Eyeballed, tune later.
export const SEAT_TARGET_MAX_DISTANCE_M = 2.2

// The floor for "looking roughly at the seat block at all" (D9) -- the
// *choice* of which free seat wins is best-alignment-wins (see
// findGazedFreeSeat below), so this only needs to exclude "looking at the
// ceiling while standing near a seat," hence a much looser cone than
// gaze.ts's tighter 12-degree nametag cone.
export const SEAT_TARGET_MIN_ALIGNMENT_COS = Math.cos(MathUtils.degToRad(35))

const seatsById = new Map(SEATS.map(seat => [seat.id, seat]))

export function getSeat(id: string): Seat | undefined {
  return seatsById.get(id)
}

// Reused across calls instead of allocating a fresh Vector3 per candidate
// seat -- mirrors gaze.ts's own module-level scratch vector convention.
const cushionScratch = new Vector3()

/**
 * D9's sit target: among free seats within `SEAT_TARGET_MAX_DISTANCE_M` of
 * `camPos` (distance to `cushion`), returns whichever has the best
 * `gazeAlignment` against its cushion, or `null` if even the best doesn't
 * clear `SEAT_TARGET_MIN_ALIGNMENT_COS`. No occlusion raycast, unlike
 * NameTag.tsx's gaze test -- the seating block is one open room well inside
 * the max distance, so "in range" already implies "not behind a wall"
 * (PLAN.md's F1 section).
 */
export function findGazedFreeSeat(
  camPos: Vector3,
  camForward: Vector3,
  occupied: ReadonlySet<string>,
): Seat | null {
  let best: Seat | null = null
  let bestAlignment = -Infinity

  for (const seat of SEATS) {
    if (occupied.has(seat.id)) continue

    cushionScratch.set(seat.cushion[0], seat.cushion[1], seat.cushion[2])
    if (cushionScratch.distanceTo(camPos) > SEAT_TARGET_MAX_DISTANCE_M) {
      continue
    }

    const alignment = gazeAlignment(camPos, camForward, cushionScratch)
    if (alignment > bestAlignment) {
      bestAlignment = alignment
      best = seat
    }
  }

  if (best === null || bestAlignment < SEAT_TARGET_MIN_ALIGNMENT_COS) {
    return null
  }
  return best
}
