{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lilnas.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "lilnas.labels" . | nindent 4 }}
type: Opaque
data:
  API_TOKEN: {{ .Values.auth.apiToken | b64enc | quote }}
  S3_ACCESS_KEY: {{ .Values.auth.minioAccessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.auth.minioSecretKey | b64enc | quote }}
{{- end }}