# Production environment overrides for equations

namespace: lilnas-apps

# Production scaling
replicaCount: 2

# Production configuration
config:
  NODE_ENV: "production"
  MINIO_HOST: "minio-api.lilnas-core"
  MINIO_PORT: "9000"
  MINIO_PUBLIC_URL: "https://storage.lilnas.io"

# Production authentication configuration
# NOTE: Secrets must be provided via CLI flags or environment variables for security
# Do not hardcode secrets in this file
secrets:
  API_TOKEN: ""  # Set via --api-token or EQUATIONS_API_TOKEN
  MINIO_ACCESS_KEY: ""  # Set via --s3-access-key or EQUATIONS_S3_ACCESS_KEY
  MINIO_SECRET_KEY: ""  # Set via --s3-secret-key or EQUATIONS_S3_SECRET_KEY

# Production resource requirements - LaTeX needs more resources
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

# Production ingress configuration
ingress:
  hosts:
    - host: equations.lilnas.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - equations.lilnas.io
      secretName: equations-lilnas-io-tls
  certManager:
    clusterIssuer: letsencrypt-prod

# Pod disruption budget for high availability
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Health check configuration with appropriate timeouts for LaTeX processing
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 45
  periodSeconds: 20
  timeoutSeconds: 10
  failureThreshold: 3

# Common labels for prod environment
commonLabels:
  environment: prod