# Development environment values for namespaces chart

# Global configuration
global:
  # Add dev environment labels
  defaultLabels:
    environment: development
    managed-by: helm
    project: lilnas

# Enable all namespaces for development
namespaces:
  core:
    enabled: true
    annotations:
      description: "Core infrastructure services (MinIO, auth, etc.)"
      environment: development
    
  apps:
    enabled: true
    annotations:
      description: "Main application services (apps, equations, etc.)"
      environment: development
    
  media:
    enabled: true
    annotations:
      description: "Media management services (Sonarr, Radarr, Emby, etc.)"
      environment: development
    
  monitoring:
    enabled: true
    annotations:
      description: "Monitoring and observability stack (Prometheus, Grafana, etc.)"
      environment: development
    
  dev:
    enabled: true
    annotations:
      description: "Development and testing environment"
      environment: development

# No resource quotas in development for flexibility
resourceQuotas:
  enabled: false

# Allow all network traffic in development
networkPolicies:
  enabled: false