# Production environment values for namespaces chart

# Global configuration
global:
  # Add production environment labels
  defaultLabels:
    environment: production
    managed-by: helm
    project: lilnas

# Production namespace configuration
namespaces:
  core:
    enabled: true
    annotations:
      description: "Core infrastructure services (MinIO, auth, etc.)"
      environment: production
      criticality: high
    
  apps:
    enabled: true
    annotations:
      description: "Main application services (apps, equations, etc.)"
      environment: production
      criticality: medium
    
  media:
    enabled: true
    annotations:
      description: "Media management services (Sonarr, Radarr, Emby, etc.)"
      environment: production
      criticality: low
    
  monitoring:
    enabled: true
    annotations:
      description: "Monitoring and observability stack (Prometheus, Grafana, etc.)"
      environment: production
      criticality: high
    
  # Disable dev namespace in production
  dev:
    enabled: false

# Enable resource quotas in production
resourceQuotas:
  enabled: true
  spec:
    hard:
      requests.cpu: "100"
      requests.memory: "200Gi"
      persistentvolumeclaims: "50"
      services.loadbalancers: "5"
      services.nodeports: "10"

# Enable network policies in production
networkPolicies:
  enabled: true
  # Allow all traffic by default, but this provides a foundation
  # for more restrictive policies to be added later
  defaultPolicy: allow-all