# Default values for namespaces
# This is a YAML-formatted file.
# Declare variables to be substituted into your templates.

# Global configuration
global:
  # Project name used in labels
  projectName: lilnas
  
  # Default labels applied to all namespaces
  defaultLabels:
    managed-by: helm
    project: lilnas

  # Default annotations applied to all namespaces
  defaultAnnotations: {}

# Namespace definitions
namespaces:
  # Core infrastructure services
  core:
    enabled: true
    name: lilnas-core
    labels:
      tier: infrastructure
    annotations:
      description: "Core infrastructure services (MinIO, auth, etc.)"
    
  # Application services
  apps:
    enabled: true
    name: lilnas-apps
    labels:
      tier: application
    annotations:
      description: "Main application services (apps, equations, etc.)"
    
  # Media stack services
  media:
    enabled: true
    name: lilnas-media
    labels:
      tier: media
    annotations:
      description: "Media management services (Sonarr, Radarr, Emby, etc.)"
    
  # Monitoring and observability
  monitoring:
    enabled: true
    name: lilnas-monitoring
    labels:
      tier: monitoring
    annotations:
      description: "Monitoring and observability stack (Prometheus, Grafana, etc.)"
    
  # Development and testing
  dev:
    enabled: true
    name: lilnas-dev
    labels:
      tier: development
    annotations:
      description: "Development and testing environment"

# Additional custom namespaces
# You can add custom namespaces here following the same structure
customNamespaces: []
# Example:
# - name: lilnas-staging
#   enabled: true
#   labels:
#     tier: staging
#   annotations:
#     description: "Staging environment"

# Resource quotas for namespaces (optional)
# These will be applied to all namespaces if enabled
resourceQuotas:
  enabled: false
  spec:
    hard:
      requests.cpu: "100"
      requests.memory: "100Gi"
      persistentvolumeclaims: "20"
      services.loadbalancers: "2"

# Network policies for namespaces (optional)
# These will be applied to all namespaces if enabled
networkPolicies:
  enabled: false
  # Allow all ingress and egress by default
  defaultPolicy: allow-all