apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
data:
  # MinIO configuration is handled via environment variables and command line args
  # This configmap is required by the common statefulset template
  placeholder: "true"