apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-console
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}