apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    service: api
spec:
  ports:
  - port: {{ .Values.service.apiPort }}
    targetPort: {{ .Values.service.apiPort }}
    protocol: TCP
    name: api
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-console
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    service: console
spec:
  ports:
  - port: {{ .Values.service.consolePort }}
    targetPort: {{ .Values.service.consolePort }}
    protocol: TCP
    name: console
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
  type: ClusterIP