apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-auth
  namespace: lilnas-core
  labels:
    app.kubernetes.io/name: forward-auth
    app.kubernetes.io/instance: forward-auth
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: lilnas
    app.kubernetes.io/managed-by: kustomize
  annotations:
    kubernetes.io/description: "OAuth2 forward authentication service for Traefik"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: forward-auth
      app.kubernetes.io/instance: forward-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: forward-auth
        app.kubernetes.io/instance: forward-auth
        app.kubernetes.io/version: "2.1.0"
        app.kubernetes.io/component: authentication
        app.kubernetes.io/part-of: lilnas
      annotations:
        kubernetes.io/description: "OAuth2 forward authentication service"
    spec:
      serviceAccountName: forward-auth
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: forward-auth
        image: thomseddon/traefik-forward-auth:2.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 4181
          protocol: TCP
        env:
        # OAuth Provider Configuration from Secret
        - name: PROVIDERS_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: forward-auth-secrets
              key: google-client-id
        - name: PROVIDERS_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: forward-auth-secrets
              key: google-client-secret
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: forward-auth-secrets
              key: secret
        # Configuration from ConfigMap
        - name: DEFAULT_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: forward-auth-config
              key: default-provider
        - name: AUTH_HOST
          valueFrom:
            configMapKeyRef:
              name: forward-auth-config
              key: auth-host
        - name: COOKIE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: forward-auth-config
              key: cookie-domain
        - name: INSECURE_COOKIE
          valueFrom:
            configMapKeyRef:
              name: forward-auth-config
              key: insecure-cookie
        - name: URL_PATH
          valueFrom:
            configMapKeyRef:
              name: forward-auth-config
              key: url-path
        - name: WHITELIST
          valueFrom:
            configMapKeyRef:
              name: forward-auth-config
              key: whitelist
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: forward-auth-config
              key: log-level
        livenessProbe:
          httpGet:
            path: /_oauth/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_oauth/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}