apiVersion: v1
kind: ServiceAccount
metadata:
  name: forward-auth
  namespace: lilnas-core
  labels:
    app.kubernetes.io/name: forward-auth
    app.kubernetes.io/instance: forward-auth
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: lilnas
    app.kubernetes.io/managed-by: kustomize
  annotations:
    kubernetes.io/description: "Service account for the forward authentication service"