services:
  yoink:
    extends:
      file: ../../infra/deploy.dev.base.yml
      service: dev-base
    environment:
      PACKAGE_NAME: yoink
    env_file:
      - ../../infra/.env.yoink
    depends_on:
      yoink-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.yoink.rule=Host(`yoink.localhost`)
      - traefik.http.services.yoink.loadbalancer.server.port=8080

  yoink-db:
    image: postgres:17-alpine
    env_file:
      - ../../infra/.env.yoink
    volumes:
      - ./data/yoink-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
