services:
  yoink:
    image: lilnas-dev
    command: -c "pnpm --filter=yoink dev"
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://yoink:yoink@yoink-db:5432/yoink
    volumes:
      - ../..:/source
    working_dir: /source
    depends_on:
      yoink-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.yoink.rule=Host(`yoink.localhost`)
      - traefik.http.services.yoink.loadbalancer.server.port=8080

  yoink-db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: yoink
      POSTGRES_PASSWORD: yoink
      POSTGRES_DB: yoink
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U yoink
      interval: 10s
      timeout: 5s
      retries: 5
