services:
  me-token-tracker:
    image: lilnas-dev
    command: -c "pnpm --filter=me-token-tracker dev"
    restart: unless-stopped
    env_file:
      - ../../infra/.env.me-token-tracker
    volumes:
      - ../../:/source
