export const EnvKeys = {
  NODE_ENV: 'NODE_ENV',
  RADARR_URL: 'RADARR_URL',
  RADARR_API_KEY: 'RADARR_API_KEY',
  SONARR_URL: 'SONARR_URL',
  SONARR_API_KEY: 'SONARR_API_KEY',
  TOKEN_SERVICE_URL: 'TOKEN_SERVICE_URL',
} as const
