# Development values for tdr-bot
# This overrides the default values.yaml for development environment

# Development namespace
namespace: lilnas-apps

# Development-specific configuration
config:
  # Use development Discord bot
  NODE_ENV: "development"
  # Development MinIO URL
  MINIO_PUBLIC_URL: "http://storage.localhost"
  # Development service URLs
  EQUATIONS_URL: "http://equations.localhost"

# Development ingress configuration
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: lilnas-core-forward-auth@kubernetescrd
    kubernetes.io/description: "Development ingress for TDR Discord bot"
  hosts:
    - host: tdr.dev.lilnas.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - tdr.dev.lilnas.io
      secretName: tdr-dev-lilnas-io-tls
  certManager:
    clusterIssuer: letsencrypt-staging

# Lower resource limits for development
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Development-specific labels
commonLabels:
  environment: dev

# Development-specific annotations
commonAnnotations:
  environment: development
  deployed-by: "development-team"

# Single replica for development
replicaCount: 1

# Disable pod disruption budget for development
podDisruptionBudget:
  enabled: false

# Disable autoscaling for development
autoscaling:
  enabled: false

# Health check configuration for development
livenessProbe:
  enabled: true
  path: /health
  port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /health
  port: http
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3