/*
 * Builds a mockup project: src/pages/*.pug -> ./*.html
 *
 * Each finished page is a single self-contained file with its CSS and JS
 * inlined — you open it from a clone with no server and no install, which is
 * the whole point of the mockups. The sharing that would otherwise happen by
 * copy-pasting an 800-line <style> block between a dozen files happens in
 * src/ instead: one theme, one layout, one set of mixins.
 *
 * Pipeline:
 *   1. render every page with Pug          -> .build/html/*.html
 *   2. run Tailwind over that HTML         -> one stylesheet for all pages
 *   3. inline the CSS + src/runtime.js, prettier the result, write ./*.html
 *
 * Tailwind scans the rendered HTML rather than the .pug sources on purpose —
 * see the note at the top of a project's src/theme.css.
 */

import tailwindcss from '@tailwindcss/postcss'
import { existsSync, watch } from 'fs'
import { mkdir, readdir, readFile, rm, writeFile } from 'fs/promises'
import * as path from 'path'
import postcss from 'postcss'
import { format, resolveConfig } from 'prettier'
import pug from 'pug'
import { pathToFileURL } from 'url'

/**
 * The layout every mockup project follows. This is convention, not
 * configuration: a designs package is `src/pages/*.pug` plus the optional
 * pieces below, and the finished pages land in the package root.
 */
const LAYOUT = {
  /** Pug basedir, and the directory watched in --watch mode. */
  src: 'src',
  /** One .pug per screen. The only required piece. */
  pages: path.join('src', 'pages'),
  /** Optional. Inlined into every page as a <style>. */
  theme: path.join('src', 'theme.css'),
  /** Optional. Inlined into every page as a <script>. */
  runtime: path.join('src', 'runtime.js'),
  /** Optional. src/data/<page>.mjs supplies that page's locals. */
  data: path.join('src', 'data'),
  /** Intermediate output; gitignored. */
  html: path.join('.build', 'html'),
} as const

const BANNER =
  '\n  Generated by `lilnas mockups build` from src/pages/%s — do not edit this file.\n' +
  '  Edit the Pug source, then run `pnpm mockups` (or `pnpm mockups:watch`).\n'

export interface MockupBuildResult {
  pages: number
  cssBytes: number
  averagePageBytes: number
  durationMs: number
}

interface RenderedPage {
  name: string
  source: string
  html: string
}

/**
 * tsc compiles this package to CommonJS, which downlevels `import()` into
 * `require()` — and `require()` cannot load the ESM `src/data/*.js` modules.
 * Going through `Function` keeps a real dynamic import in the emitted output.
 */
const importModule = new Function('specifier', 'return import(specifier)') as (
  specifier: string,
) => Promise<{ default?: unknown }>

/**
 * A page's copy and sample data, if it has any: src/data/<page>.mjs, default-
 * exporting an object that becomes the template's locals.
 *
 * This exists because of a Pug scoping rule. A template that `extends` a
 * layout may only have named blocks and mixins at its top level, so page
 * constants have to go inside `block content` — and Pug compiles that block
 * into its own function, which the page's mixins (defined at the top level)
 * can't see. Locals are visible everywhere, mixins included. It also keeps the
 * .pug files to layout, which is the point of the exercise.
 *
 * `.mjs` first: a designs directory needn't be an npm package, so there may be
 * no package.json declaring `"type": "module"` — and without one Node has to
 * guess at a bare `.js`, which it does by failing to parse it as CommonJS and
 * warning on every build. `.js` still works for a project that is a package.
 */
async function loadData(
  dir: string,
  page: string,
  revision: number,
): Promise<pug.LocalsObject> {
  const file = ['mjs', 'js']
    .map(ext => path.join(dir, LAYOUT.data, `${page}.${ext}`))
    .find(existsSync)
  if (!file) {
    return {}
  }

  // The query string busts Node's module cache, so a rebuild in --watch mode
  // picks up edits to the data file instead of the copy loaded on first build.
  const module = await importModule(
    `${pathToFileURL(file).href}?rev=${revision}`,
  )
  return (module.default ?? module) as pug.LocalsObject
}

/** Render every src/pages/*.pug into .build/html. */
async function renderPages(
  dir: string,
  revision: number,
): Promise<RenderedPage[]> {
  const pagesDir = path.join(dir, LAYOUT.pages)
  const htmlDir = path.join(dir, LAYOUT.html)

  const files = (await readdir(pagesDir)).filter(f => f.endsWith('.pug')).sort()
  if (files.length === 0) {
    throw new Error(`No pages found in ${LAYOUT.pages}`)
  }

  await rm(htmlDir, { recursive: true, force: true })
  await mkdir(htmlDir, { recursive: true })

  const pages: RenderedPage[] = []
  for (const file of files) {
    const name = file.replace(/\.pug$/, '')
    const filename = path.join(pagesDir, file)
    const html = pug.renderFile(filename, {
      basedir: path.join(dir, LAYOUT.src),
      filename,
      ...(await loadData(dir, name, revision)),
    })
    await writeFile(path.join(htmlDir, `${name}.html`), html)
    pages.push({ name, source: file, html })
  }
  return pages
}

/**
 * Compile the theme against whatever classes the rendered pages actually use.
 * One stylesheet is built for all pages and inlined into each: the pages share
 * nearly all of their vocabulary, so per-page builds would mostly duplicate
 * this anyway, and one shared blob means one thing to diff when it changes.
 */
async function buildCss(
  dir: string,
  warn: (message: string) => void,
): Promise<string> {
  const themePath = path.join(dir, LAYOUT.theme)
  if (!existsSync(themePath)) {
    return ''
  }

  const theme = await readFile(themePath, 'utf8')
  const result = await postcss([
    tailwindcss({ base: path.join(dir, LAYOUT.src), optimize: true }),
  ]).process(theme, { from: themePath, to: undefined })

  for (const warning of result.warnings()) {
    warn(`tailwind: ${warning.toString()}`)
  }
  return result.css
}

/** Inline the stylesheet and runtime into a rendered page. */
function inline(
  html: string,
  { css, js, source }: { css: string; js: string; source: string },
): string {
  const head = [
    `<!--${BANNER.replace('%s', source)}-->`,
    css.trim() ? `<style>\n${css}\n</style>` : '',
    js.trim() ? `<script>\n${js}\n</script>` : '',
  ]
    .filter(Boolean)
    .join('\n')

  if (!html.includes('</head>')) {
    throw new Error(`Rendered page ${source} has no </head> to inline into`)
  }
  return html.replace('</head>', `${head}\n</head>`)
}

/**
 * Builds one mockup project. `revision` only needs to change between rebuilds
 * of the same process, so that watch mode reloads src/data modules.
 */
export async function buildMockups(
  dir: string,
  options: { warn?: (message: string) => void; revision?: number } = {},
): Promise<MockupBuildResult> {
  const { warn = () => {}, revision = 0 } = options
  const started = Date.now()

  const pages = await renderPages(dir, revision)
  const css = await buildCss(dir, warn)
  const js = await readFile(path.join(dir, LAYOUT.runtime), 'utf8').catch(
    () => '',
  )
  const prettierConfig = await resolveConfig(path.join(dir, 'index.html'))

  let bytes = 0
  for (const { name, source, html } of pages) {
    const formatted = await format(inline(html, { css, js, source }), {
      ...prettierConfig,
      parser: 'html',
    })
    await writeFile(path.join(dir, `${name}.html`), formatted)
    bytes += Buffer.byteLength(formatted)
  }

  return {
    pages: pages.length,
    cssBytes: Buffer.byteLength(css),
    averagePageBytes: Math.round(bytes / pages.length),
    durationMs: Date.now() - started,
  }
}

/**
 * Watches a project's src/ and rebuilds on save. Never resolves — the caller
 * runs until interrupted.
 */
export function watchMockups(
  dir: string,
  handlers: {
    onBuild: (result: MockupBuildResult) => void
    onError: (error: Error) => void
    warn?: (message: string) => void
  },
): Promise<never> {
  let revision = 0
  let queued: NodeJS.Timeout | undefined

  watch(path.join(dir, LAYOUT.src), { recursive: true }, (_event, file) => {
    if (!file || path.basename(file).startsWith('.')) {
      return
    }
    clearTimeout(queued)
    queued = setTimeout(() => {
      revision += 1
      buildMockups(dir, { warn: handlers.warn, revision }).then(
        handlers.onBuild,
        handlers.onError,
      )
    }, 40)
  })

  return new Promise<never>(() => {})
}
