services:
  portal:
    image: lilnas-dev
    command: -c "pnpm --filter=portal dev"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../..:/source
    working_dir: /source
    labels:
      - traefik.enable=true
      - traefik.http.routers.portal.rule=Host(`portal.localhost`)
      - traefik.http.services.portal.loadbalancer.server.port=8080
