# Development values for cert-manager-issuers
# This uses the staging issuer by default to avoid rate limits

# Use a development email if different
email: admin@lilnas.io

# Enable only staging in development
staging:
  enabled: true
  name: letsencrypt-staging
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  privateKeySecretRef:
    name: letsencrypt-staging

# Disable production issuer in dev to avoid accidental rate limiting
production:
  enabled: false