# Storage Classes for lilnas k8s cluster
# These define different storage tiers based on the underlying storage medium

{{- if .Values.storageClasses.hdd.enabled }}
---
# Default storage class for general HDD-based storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.hdd.name }}
  labels:
    {{- include "storage-setup.labels" . | nindent 4 }}
  {{- if .Values.storageClasses.hdd.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.provisioner }}
parameters:
  nodePath: {{ .Values.storageClasses.hdd.nodePath }}
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumeBindingMode }}
{{- end }}

{{- if .Values.storageClasses.hddMedia.enabled }}
---
# Storage class for media files on HDD
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.hddMedia.name }}
  labels:
    {{- include "storage-setup.labels" . | nindent 4 }}
  {{- if .Values.storageClasses.hddMedia.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.provisioner }}
parameters:
  nodePath: {{ .Values.storageClasses.hddMedia.nodePath }}
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumeBindingMode }}
{{- end }}

{{- if .Values.storageClasses.ssd.enabled }}
---
# Storage class for fast SSD storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.ssd.name }}
  labels:
    {{- include "storage-setup.labels" . | nindent 4 }}
  {{- if .Values.storageClasses.ssd.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.provisioner }}
parameters:
  nodePath: {{ .Values.storageClasses.ssd.nodePath }}
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumeBindingMode }}
{{- end }}

{{- if .Values.storageClasses.ssdPhotos.enabled }}
---
# Storage class for photos on SSD
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.ssdPhotos.name }}
  labels:
    {{- include "storage-setup.labels" . | nindent 4 }}
  {{- if .Values.storageClasses.ssdPhotos.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ .Values.provisioner }}
parameters:
  nodePath: {{ .Values.storageClasses.ssdPhotos.nodePath }}
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumeBindingMode }}
{{- end }}