apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lilnas.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "lilnas.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  STORAGE_PROVIDER: {{ .Values.config.storageProvider | quote }}
  STORAGE_PATH: {{ .Values.config.storagePath | quote }}
  S3_ENDPOINT: {{ .Values.config.s3Endpoint | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  PORT: {{ .Values.config.port | quote }}