apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "turbo-cache.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "turbo-cache.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Configuration for Turborepo remote cache service"
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  STORAGE_PROVIDER: {{ .Values.config.storageProvider | quote }}
  STORAGE_PATH: {{ .Values.config.storagePath | quote }}
  S3_ENDPOINT: {{ .Values.config.s3Endpoint | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  PORT: {{ .Values.config.port | quote }}