{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turbo-cache.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "turbo-cache.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/description: "Secret for Turborepo remote cache authentication"
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- if .Values.auth.turboToken }}
  TURBO_TOKEN: {{ .Values.auth.turboToken | quote }}
  {{- end }}
  {{- if .Values.auth.s3AccessKey }}
  S3_ACCESS_KEY: {{ .Values.auth.s3AccessKey | quote }}
  {{- end }}
  {{- if .Values.auth.s3SecretKey }}
  S3_SECRET_KEY: {{ .Values.auth.s3SecretKey | quote }}
  {{- end }}
{{- end }}