{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lilnas.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "lilnas.labels" . | nindent 4 }}
type: Opaque
data:
  TURBO_TOKEN: {{ .Values.auth.turboToken | b64enc | quote }}
  S3_ACCESS_KEY: {{ .Values.auth.s3AccessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.auth.s3SecretKey | b64enc | quote }}
{{- end }}