apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lilnas-core

resources:
  - ../base

labels:
  - pairs:
      environment: prod

# Production-specific patches
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: turbo-cache
    spec:
      replicas: 2
      template:
        spec:
          containers:
          - name: turbo-cache
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: turbo-cache-config
    data:
      LOG_LEVEL: "warn"