name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      model:
        description: 'Claude model to use'
        required: false
        default: 'claude-sonnet-4-20250514'
        type: choice
        options:
          - claude-sonnet-4-20250514
          - claude-opus-4-20250514
          - claude-haiku-4-20250514

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Parse model from comment
        id: parse_model
        run: |
          # Default model
          MODEL="claude-sonnet-4-20250514"

          # Check workflow dispatch input first
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ inputs.model }}" ]; then
            MODEL="${{ inputs.model }}"
          else
            # Parse comment body for model selection
            COMMENT_BODY=""
            if [ "${{ github.event_name }}" == "issue_comment" ]; then
              COMMENT_BODY="${{ github.event.comment.body }}"
            elif [ "${{ github.event_name }}" == "pull_request_review_comment" ]; then
              COMMENT_BODY="${{ github.event.comment.body }}"
            elif [ "${{ github.event_name }}" == "pull_request_review" ]; then
              COMMENT_BODY="${{ github.event.review.body }}"
            elif [ "${{ github.event_name }}" == "issues" ]; then
              COMMENT_BODY="${{ github.event.issue.body }}"
            fi

            # Parse model from comment (case insensitive)
            if echo "$COMMENT_BODY" | grep -iE "@claude.*(opus|--model=opus|use opus)" > /dev/null; then
              MODEL="claude-opus-4-20250514"
            elif echo "$COMMENT_BODY" | grep -iE "@claude.*(haiku|--model=haiku|use haiku)" > /dev/null; then
              MODEL="claude-haiku-4-20250514"
            elif echo "$COMMENT_BODY" | grep -iE "@claude.*(sonnet|--model=sonnet|use sonnet)" > /dev/null; then
              MODEL="claude-sonnet-4-20250514"
            fi
          fi

          echo "model=$MODEL" >> $GITHUB_OUTPUT
          echo "Using Claude model: $MODEL"

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Check kubectl secrets
        id: check_kubectl
        run: |
          if [ -n "${{ secrets.KUBE_TOKEN }}" ]; then
            echo "has_kubectl_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has_kubectl_secrets=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup kubectl
        if: steps.check_kubectl.outputs.has_kubectl_secrets == 'true'
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CA_CERT }}" | base64 -d > ~/.kube/ca.crt
          kubectl config set-cluster github-actions --server=${{ secrets.KUBE_SERVER }} --certificate-authority=~/.kube/ca.crt
          kubectl config set-credentials github-actions --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context github-actions --cluster=github-actions --user=github-actions --namespace=${{ secrets.KUBE_NAMESPACE || 'default' }}
          kubectl config use-context github-actions

      - name: Verify kubectl connection
        if: steps.check_kubectl.outputs.has_kubectl_secrets == 'true'
        run: |
          echo "Testing kubectl connection..."
          kubectl cluster-info
          kubectl get nodes --no-headers | wc -l | xargs -I {} echo "Found {} nodes in cluster"

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: ${{ steps.parse_model.outputs.model }}

          allowed_tools: |
            Bash
            mcp__sequential-thinking__sequentialthinking
            mcp__playwright__browser_close
            mcp__playwright__browser_resize
            mcp__playwright__browser_console_messages
            mcp__playwright__browser_handle_dialog
            mcp__playwright__browser_file_upload
            mcp__playwright__browser_install
            mcp__playwright__browser_press_key
            mcp__playwright__browser_navigate
            mcp__playwright__browser_navigate_back
            mcp__playwright__browser_navigate_forward
            mcp__playwright__browser_network_requests
            mcp__playwright__browser_pdf_save
            mcp__playwright__browser_take_screenshot
            mcp__playwright__browser_snapshot
            mcp__playwright__browser_click
            mcp__playwright__browser_drag
            mcp__playwright__browser_hover
            mcp__playwright__browser_type
            mcp__playwright__browser_select_option
            mcp__playwright__browser_tab_list
            mcp__playwright__browser_tab_new
            mcp__playwright__browser_tab_select
            mcp__playwright__browser_tab_close
            mcp__playwright__browser_generate_playwright_test
            mcp__playwright__browser_wait_for
            mcp__fetch__imageFetch
            mcp__context7__resolve-library-id
            mcp__context7__get-library-docs

          custom_instructions: |
            You are working on the LilNAS monorepo - a self-hosted NAS system with multiple integrated services.

            ## Repository Structure
            - Monorepo using pnpm workspaces with Turbo build orchestration
            - TypeScript throughout (avoid 'any' types)
            - IMPORTANT: Check CLAUDE.md for detailed development instructions

            ## Package Types & Key Patterns

            ### Frontend Apps
            - @lilnas/apps (Next.js 14): Portal/dashboard using App Router, Tailwind CSS, Jotai for state
            - @lilnas/dashcam (Vite+React): Video viewer application

            ### Backend Services (NestJS)
            - @lilnas/equations: LaTeX rendering (SECURITY CRITICAL - see SECURITY.md)
            - @lilnas/me-token-tracker: Crypto tracking Discord bot

            ### Full-Stack Apps (NestJS + Next.js)
            - @lilnas/tdr-bot: AI Discord bot with LangChain/OpenAI integration
            - @lilnas/download: Video download service with yt-dlp/ffmpeg

            ### Development Tools
            - @lilnas/cli: Docker Compose management (./lilnas command)
            - @lilnas/utils, eslint-config, prettier-config: Shared configs

            ## Key Commands
            - Build: pnpm run build (uses Turbo caching)
            - Test: pnpm test (Jest)
            - Lint/Format: pnpm run lint:fix
            - Service management: ./lilnas dev [start|stop|logs]
            - Kubernetes: kubectl (available if KUBE_TOKEN secret is configured)

            ## Critical Guidelines
            1. Follow existing patterns in the codebase
            2. Security: Never expose secrets, validate inputs, use secure spawn
            3. Use workspace:* for cross-package dependencies
            4. Multi-stage Docker builds for production
            5. Test coverage expected for new features
            6. Run lint and type-check before completing tasks

            ## Infrastructure
            - Traefik reverse proxy with Let's Encrypt SSL
            - MinIO for S3-compatible storage
            - Docker Compose for orchestration
            - Kubernetes cluster with RBAC-enabled access
            - Development: *.localhost domains
            - Production: *.lilnas.io domains

            When in doubt, refer to CLAUDE.md for detailed instructions and patterns.

          mcp_config: |
            {
              "mcpServers": {
                "sequential-thinking": {
                  "command": "npx",
                  "args": [
                    "-y",
                    "@modelcontextprotocol/server-sequential-thinking"
                  ]
                },
                "playwright": {
                  "command": "npx",
                  "args": [
                    "-y",
                    "@playwright/mcp@latest"
                  ]
                },
                "fetch": {
                  "command": "npx",
                  "args": [
                    "-y",
                    "@modelcontextprotocol/server-fetch"
                  ]
                },
                "context7": {
                  "transport": {
                    "type": "http",
                    "url": "https://mcp.context7.com/mcp"
                  }
                }
              }
            }
