# Production values for dashcam
# This overrides the default values.yaml for production deployment

# Image configuration
image:
  tag: "latest"
  pullPolicy: Always

# Ingress configuration for production
ingress:
  hosts:
    - host: dashcam.lilnas.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dashcam.lilnas.io
      secretName: dashcam-lilnas-io-tls
  certManager:
    clusterIssuer: letsencrypt-prod

# Production security hardening
podSecurityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 101  # nginx user
  runAsGroup: 101  # nginx group
  fsGroup: 101
  seccompProfile:
    type: RuntimeDefault

# Production resource limits
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"

# Production health checks
livenessProbe:
  enabled: true
  path: /
  port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /
  port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Production annotations
commonAnnotations:
  kubernetes.io/description: "Dashcam video viewer - Production deployment"
  kubernetes.io/managed-by: "helm"
  environment: "production"

# Production deployment strategy
revisionHistoryLimit: 3

# Production volume configuration
tmpVolume:
  enabled: true
  sizeLimit: 100Mi

cacheVolume:
  enabled: false