{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radarr.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
  annotations:
    {{- include "radarr.annotations" . | nindent 4 }}
data:
  {{- with .Values.config }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}