apiVersion: v1
kind: Service
metadata:
  name: {{ include "radarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: service
  annotations:
    {{- include "radarr.annotations" . | nindent 4 }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "radarr.selectorLabels" . | nindent 4 }}